apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: placide-ns
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 1
  template:
    metadata:
      name: zookeeper
      labels:
        app: zookeeper
    spec:
      serviceAccountName: placide-svc-account
      containers:
        - name: zookeeper
          image: zookeeper:3.4.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: zoo-port
              hostPort: 2181
          startupProbe:
            tcpSocket:
              port: zoo-port
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: zoo-port
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zoo-port
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
  namespace: placide-ns
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
      nodePort: 30181
      name: zoo-port
  type: NodePort


