# create a 'namespace'
apiVersion: v1
kind: Namespace
metadata:
  name: placide-ns
  labels:
    app: placide-ns
---
# create service account in the namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: placide-svc-account
  labels:
    app: placide-svc-account
  namespace: placide-ns
---
# create 'role' that will be connected to created service account
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: placide-admin
  labels:
    app: placide-admin
  namespace: placide-ns
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
## create a 'role binding' to bind created role to service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: placide-admin-rolebinding
  labels:
    app: placide-admin-rolebinding
  namespace: placide-ns
roleRef:
  kind: Role
  name: placide-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: placide-svc-account
    namespace: placide-ns